# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170131_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/static/blog/images/', verbose_name='Image'),
        ),
    ]
